name: test-fortran-ubuntu

on: [push, pull_request]

jobs:
  fast_build_release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        toolchain:
          - {compiler: gcc, version: 13}
          - {compiler: intel, version: '2023.2'}
          # - {compiler: nvidia-hpc, version: '23.11'}

    steps:
      - uses: actions/checkout@v4

      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DFORTRAN=ON -DFAST_BUILD=ON

      - name: Build
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --parallel --config Release

      - name: Test
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: ctest --timeout 300 --output-on-failure -C Release

      - name: Test Fortran
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          ls 
          ./bin/Release/fortrantest

 